# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog Chrìstein
description: > # this means to ignore newlines until "baseurl:"
  Blog mu Apple, teicneòlas is pròiseactan Chrìstein MhicMhìcheil

#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://angeidheal.scot" # the base hostname & protocol for your site

#footer
author: Crìstean MacMhìcheil
website: "https://angeidheal.scot/"
mastodon: https://criomagan.scot/@angeidheal
bluesky: https://bsky.app/profile/angeidheal.scot.bsky.social
instagram: 
threads: 
github: https://github.com/angeidheal
email: fios@angeidheal.scot

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/

# No. of posts on homepage
paginate: 8
paginate_path: /duilleag-:num/

# Sass style
# sass:
#  style: compressed

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
