# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Criomagan
description: > # this means to ignore newlines until "baseurl:"
  Blog mu Apple, teicneòlas is pròiseactan Chrìstein MhiMhìcheil

#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://criomagan.scot" # the base hostname & protocol for your site

#footer
author-name: Crìstean MacMhìcheil
author-website: "https://criomagan.scot/"
author-bio: |
  Is mise Crìstean MacMhìcheil. Rugadh is thogadh mi ann an Siorrachd Rois.
  Cheumnaich mi bho Sabhal Mòr Ostaig ann an 2010 le BA (le Urram) ann an Gàidhlig is Leasachadh.
  Ann an 2007, stèidhich mi AbairThusa[^1], a bha na chiad lìonra sòisealta Ghàidhlig, ach dhùin e ann an 2012.
  Nuair a bha mi na b’ òige, cha robh mi eòlach air Gèidheil (Gàidheil LGDTC+) sam bith eile agus mar sin stèidhich mi am buidheann Bebo ‘GayGaels’ airson àite a thoirt do Ghèidheil a bhith a’ conaltradh ri chèile.
  Ann an 2008, stèidhich mi am blog naidheachd LGDTC+, An Gèidheal Ùr[^2].
  Ann an 2020, chruthaich mi an t‑seirbheis aimsir Ghàidhlig[^3], Aimsir.scot.
  Tha mi nam bhìogan.

#social
mastodon: https://abairthusa.scot/@angeidheal
github: https://github.com/angeidheal
email: fios@criomagan.scot

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 12
paginate_path: /duilleag-:num/

# Sass style
# sass:
#  style: compressed

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
